version: "3.7"

services:
  petsy-search:
    image: michaelkoconnor/petsy-search-go
    environment:
      NODE_ENV: production
    ports:
      - 5001:5001
    env_file: .env
    restart: unless-stopped
